### ISSUE TITLE
Error with tables without pk

### ISSUE THREAD

**Issue by jameswpm** [bruunofco/easyfast#1]
When I use a table without a primary key and try to do a insertion I receive the error:

`Fatal error: Cannot access empty property in Model line 396`.

After debug, it's possible to see the erro in line 67 of the trait Insert:

`return $this->lastInsertId();`

Apparently, the method `lastInsertId()` does not exist in these cases.

**Comment by hiagodotme** [comment]
Has the issue been fixed.
